### ISSUE TITLE
Footer Responsiveness

### ISSUE THREAD

**Issue by caiobukvar** [caiobukvar/br-adv#32]
![image](https://github.com/caiobukvar/br-adv/assets/78058375/85acda43-964e-4942-ad09-c85e0553dd74)
**For width < 1024px `flex-direction: column`
For width > 1024px keep the original**

- [x] **mobile:** < 375px
- [x] **mobile large:**  375px - 425px
- [x] **tablet:** 768px - 1024px
- [x] **desktop:** > 1024px

**Comment by Basavarajakjbasuu** [comment]
Can I work on this issue

**Comment by caiobukvar** [comment]
> Can I work on this issue

Hello! Well, you can make a pull request and I can review it, sure! Any help is welcome.

**Comment by caiobukvar** [comment]
@Basavarajakjbasuu I have done it, if you want to check how it came out, code is already deployed!
